# Generated by Django 6.0.7 on 2026-07-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
