# Generated by Django 6.0.7 on 2026-07-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creat_date']},
        ),
    ]
