# Generated by Django 6.0.7 on 2026-07-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creat_date']},
        ),
    ]
